name: deploy_static_website

on:
    push:
        branches: [ main ]


# File: .github/workflows/workflow.yml


jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v5
    - name: Deploy the website
      uses: tibor19/static-website-deploy@v4
      with:
        enabled-static-website: 'true'
        folder: '.'
        connection-string: ${{ secrets.CONNECTION_STRING }}

